version: "3.9"

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  create:
    build:
      context: .
      dockerfile: Dockerfile-create
    environment:
      MONGO_HOST: mongodb
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  list:
    build:
      context: .
      dockerfile: Dockerfile-list
    environment:
      MONGO_HOST: mongodb
    ports:
      - 8081:8081
    depends_on:
      - mongodb
